### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by CammyEnn** [Naodo/HackAndSlashTemplate#3]
Dear Arnaud,
I have a problem with your template.
I am using the new version of Unreal Engine 5 at home and at school, the 5.02 version. 
I don't know how or why, but I can't open your template (and I mean your template, not your final build) on my personal computer, at home.
I could open it with the former version from before (the 5.01), and with the new version, but only at school. (?????)
Did I do something that I shouldn't have done? Perhaps, I should have stayed with the 5.01? 

Best regards,

J. Tranquillin

**Comment by Naodo** [comment]
Hello,

After some investigation, I fixed the problem by removing & clonning again the template , launch the template by double clicking on the .uproject file in the template folder, a popup will show up asking you if you want to rebuild modules, click on "Yes", then wait a few moment, it can takes a while according to your pc's performances but eventually the project should open now.

Let me know if it fixed the problem on your side.

**Comment by CammyEnn** [comment]
Sorry. It doesn't work. 
![Erreur](https://user-images.githubusercontent.com/102595982/171745673-3870ebe2-5425-4746-951e-1b2304fce886.jpg)

**Comment by Naodo** [comment]
Try right clicking on the uproject file and select "Generate visual studio project file", it should fix this problem.

**Comment by CammyEnn** [comment]
This time, it worked.
Thank you.
